### ISSUE TITLE
用这个固件 看虎牙直播打开特别慢

### ISSUE THREAD

**Issue by assasec** [firker/openwrt-Exclusive#21]
用这个固件 看虎牙直播打开特别慢 换别动固件秒开 看优酷视频缓冲也很慢

**Comment by firker** [comment]
表达不清楚  无法定位问题 本人自用4.19固件没有你说的现象 每个人的固件也有细微的差距  有的插件使用方法也有不同  无论哪个固件适合自己用就行了

**Comment by assasec** [comment]
> 表达明显无法定位问题本人自用4.19固件没有你说的现象每个人的固件也有细微的差异有的插件使用方法也有不同的固件适合自己用就行了
