### ISSUE TITLE
新版5.4编译失败，希望重新编译

### ISSUE THREAD

**Issue by lzqd** [firker/openwrt-Exclusive#38]
新版5.4编译失败，希望重新编译

**Comment by firker** [comment]
> 新版5.4编译失败，希望重新编译

正在抢修

**Comment by tianbinhai** [comment]
好像源码那边出全变成5.10  我刚刚自己虚拟机编译的怎么样都是5.10

**Comment by firkerword** [comment]
> 好像源码那边出全变成5.10 我刚刚自己虚拟机编译的怎么样都是5.10

默认就是5.10

**Comment by tianbinhai** [comment]
之前不是5.4吗
我找找之前的包看看可能我记错了

**Comment by firkerword** [comment]
> 之前不是5.4吗
> 我找找之前的包看看可能我记错了

嗯之前是  现在是5.10

**Comment by tianbinhai** [comment]
我还以为我搞错什么了
要改源码切换重新编译了  不过我这洋垃圾24线程挺快
