### ISSUE TITLE
2022.5.11版本5.10内核 控制台疯狂输出test 512

### ISSUE THREAD

**Issue by masterc24** [firker/openwrt-Exclusive#47]
![屏幕截图 2022-05-15 225534](https://user-images.githubusercontent.com/19277292/168479324-b2d7e2c7-c732-4581-8bf9-0670b4a18c6c.png)

**Comment by firker** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
